export const Banks = [
    "1st Valley Bank, Inc. A Development Bank",
    "Advance Credit Bank (A Rural Bank) Corp.",
    "Agribusiness Rural Bank, Inc.",
    "Agricultural Bank of the Philippines, Inc. (A Rural Bank)",
    "Al-Amanah Islamic Investment Bank of the Philippines",
    "Aliaga Farmers Rural Bank, Inc.",
    "AllBank (A Thrift Bank), Inc.",
    "Anilao Bank (Rural Bank of Anilao (Iloilo), Inc.",
    "ARDCIBank, Inc., A Rural Bank",
    "ASENSO Rural Bank of Bautista, Inc.",
    "Asia United Bank Corporation",
    "Aspac Rural Bank, Inc.",
    "Aurorabank (A Rural Bank), Inc.",
    "Australia and New Zealand Banking Group Limited",
    "Baclaran Rural Bank, Inc.",
    "Balanga Rural Bank, Inc.",
    "Baliuag Rural Bank, Inc.",
    "Banco Abucay, Inc.",
    "Banco Alabang, Inc. (A Rural Bank)",
    "Banco Bakun, Inc. (A Rural Bank)",
    "Banco Cooperativa De Zamboanga",
    "Banco De Calamba, Inc. (A Rural Bank)",
    "Banco de Mindoro, Inc. (A Rural Bank)",
    "Banco Mexico, Inc. (A Rural Bank)",
    "Banco Rural De Isla Cordova (Cebu), Inc.",
    "Banco San Vicente, Inc. (A Rural Bank)",
    "Banco Santiago De Libon, Inc., (A Rural Bank)",
    "Banco Sual (A Rural Bank), Inc.",
    "Bangko Kabayan, Inc. (A Private Development Bank)",
    "Bangko Kaisa, Inc. (Formerly: Rural Bank of Bugasong (Antique), Inc.)",
    "Bangko Mabuhay (A Rural Bank), Inc.",
    "Bangko Magsaysay (Isabela), Inc. - A Rural Bank",
    "Bangko Montañosa, Inc. (A Rural Bank)",
    "Bangko ng Kabuhayan, (A Rural Bank) Inc.",
    "Bangko Nuestra Senora Del Pilar, Inc. (A Rural Bank)",
    "Bangko Pasig (Rural Bank)",
    "Bangko Rural ng San Teodoro, Inc.",
    "Bangkok Bank Public Company Limited",
    "Bank of America, N.A.",
    "Bank of China (Hongkong) Limited-Manila Branch",
    "Bank of Commerce",
    "Bank of Hope, Inc. (A Rural Bank)",
    "Bank of Makati (A Savings Bank), Inc.",
    "Bank of Ormoc, Inc. (A Rural Bank)",
    "Bank of the Philippine Islands",
    "Bank One Savings Corporation",
    "Banko Zambaleño Inc., (BZI) (A Rural Bank)",
    "Bankways, Inc. (A Rural Bank)",
    "Bannawag Bank, Inc. (A Rural Bank)",
    "Bataan Development Bank",
    "Batangas Rural Bank for Cooperatives, Inc.",
    "Bayanihan Bank, Inc",
    "Baybank, Inc. (A Rural Bank)",
    "BDO Network Bank, Inc. (A Rural Bank)",
    "BDO Private Bank, Inc.",
    "BDO Unibank, Inc.",
    "Benguet Center Bank, Inc. A Rural Bank",
    "BHF Rural Bank, Inc.",
    "BINHI Rural Bank, Inc. (Formerly: Rural Bank of Balingasag (Misamis Oriental), Inc.)",
    "Biñan Rural Bank, Inc.",
    "BOF, Inc. (A Rural Bank)",
    "Bolbok Rural Bank, Inc.",
    "BPI Direct BanKO, Inc., A Savings Bank",
    "Bridgeway Rural Banking Corporation",
    "Bukidnon Bank, Inc. (A Rural Bank)",
    "Butuan City Rural Bank, Inc.",
    "Cagsawa Rural Bank, Inc.",
    "Camalig Bank, Inc. (A Rural Bank)",
    "Camiling Rural Bank, Inc.",
    "Cantilan Bank, Inc. (A Rural Bank)",
    "Card Bank, Inc. (A Microfinance - Oriented Rural Bank)",
    "CARD MRI Rizal Bank, Inc., A Microfinance-Oriented Rural Bank",
    "CARD SME Bank, Inc. A Thrift Bank",
    "Caritas Banco ng Masa, Inc. (A Rural Bank)",
    "Cathay United Bank Co., LTD. - Manila Branch",
    "Cavite United Rural Bank, Corporation",
    "Cebuana Lhuillier Rural Bank, Inc.",
    "Century Rural Bank, Inc.",
    "Century Savings Bank Corporation",
    "Chang Hwa Commercial Bank, Ltd. - Manila Branch",
    "China Bank Savings, Inc.",
    "China Banking Corporation",
    "CIMB Bank Philippines Inc.",
    "Citibank, N.A.",
    "Citizen's Rural Bank (Cabiao), Inc.",
    "City Savings Bank, Inc.",
    "Citystate Savings Bank, Inc.",
    "Classic Rural Bank, Inc.",
    "Common Wealth Rural Bank, Inc.",
    "Community Rural Bank of Dapitan City, Incorporated",
    "Community Rural Bank of Medellin (Cebu), Inc.",
    "Community Rural Bank of San Felipe (Zambales), Inc.",
    "Community Rural Bank of San Gabriel (La Union), Inc.",
    "Cooperative Bank of Benguet (CBB)",
    "Cooperative Bank of Bohol",
    "Cooperative Bank of Cagayan",
    "Cooperative Bank of Cebu",
    "Cooperative Bank of Cotabato",
    "Cooperative Bank of La Union",
    "Cooperative Bank of Mt. Province",
    "Cooperative Bank of Negros Oriental",
    "Cooperative Bank of Nueva Vizcaya",
    "Cooperative Bank of Palawan",
    "Cooperative Bank of Quezon Province",
    "Cooperative Bank of Zambales",
    "Cordillera Bank, Inc. (A Rural Bank)",
    "Cordillera Savings Bank, Inc.",
    "Crown Bank, Inc. (A Rural Bank)",
    "CSFirst Bank, INC. -A Rural Bank",
    "CTBC Bank (Philippines) Corporation",
    "Cuyapo Rural Bank, Inc.",
    "Deutsche Bank AG",
    "Development Bank of the Philippines",
    "Diamond Rural Bank, Inc.",
    "Dumaguete City Development Bank, Inc.",
    "Dumaguete Rural Bank, Inc.",
    "Dungganon Bank (A Microfinance Rural Bank), Inc.",
    "East West Banking Corporation",
    "East West Rural Bank, Inc.",
    "ECCOBANK (A Rural Bank) Inc.",
    "Emerald Rural Bank, Inc.",
    "Enterprise Bank, Inc. (A Rural Bank)",
    "Enterprise Capital Bank, Inc. (Taguig Rural Bank)",
    "Entrepreneur Rural Bank, Inc.",
    "Equicom Savings Bank, Inc.",
    "Far Eastern Bank (A Rural Bank) Inc.",
    "Farm Bank, Inc. (A Rural Bank)",
    "FBC First Bank of Calaca, Inc.",
    "Filidian Rural Bank of Antipolo Inc.",
    "First Commercial Bank, Ltd., Manila Branch",
    "First Community Bank, Inc. (A Rural Bank)",
    "First Consolidated Bank, Inc. (A Private Development Bank)",
    "First Imperial Business Bank, Inc. (A Rural Bank)",
    "First Integrity Bank, Inc. (Rural Bank of Bailen)",
    "First Isabela Cooperative Bank, Inc. (Ficobank)",
    "First Mindoro Microfinance Rural Bank, Inc.",
    "First Philippine Partners Bank, Inc. (A Rural Bank)",
    "First State Bank, Inc., A Rural Bank",
    "First Tagum Rural Bank, Inc.",
    "First United Farmers Rural Bank, Inc.",
    "Frontier Rural Bank, Inc.",
    "Gateway Rural Bank, Inc.",
    "GM Bank of Luzon, Inc. (A Rural Bank)",
    "Golden Rural Bank of the Philippines, Inc.",
    "Guagua Rural Bank, Inc.",
    "Guagua Savers Bank (A Rural Bank), Inc.",
    "Highland Rural Bank Inc.",
    "Hiyas Banking Corporation (A Thrift Bank)",
    "Hua Nan Commercial Bank, Ltd. - Manila Branch",
    "Ilocos Consolidated Cooperative Bank",
    "Imus Rural Bank, Inc.",
    "Industrial and Commercial Bank of China Limited - Manila Branch",
    "Industrial Bank of Korea Manila Branch",
    "ING Bank N.V.",
    "Innovative Bank  Inc. (A Rural Bank)",
    "ISLA Bank (A Thrift Bank), Inc.",
    "Janiuay Rural Bank, Inc.",
    "JP Morgan Chase Bank, N.A.",
    "Katipunan Banking Corporation (A Rural Bank)",
    "KEB Hana Bank - Manila Branch",
    "Key Rural Bank, Inc.",
    "Lagawe Highlands Rural Bank, Inc.",
    "Laguna Prestige Banking Corporation, (A Rural Bank)",
    "Land Bank of the Philippines",
    "Legazpi Savings Bank, Inc.",
    "Lemery Savings and Loan Bank, Inc.",
    "Liberty Bank (A Rural Bank), Inc.",
    "Life Savings Bank, Inc.",
    "LifeBank- A Rural Bank",
    "Limcoma Rural Bank, Inc.",
    "Lipa Bank, Inc. (A Rural Bank)",
    "LOLC Bank Philippines Incorporated (A Thrift Bank)",
    "LUDB Bank, Inc. (A Rural Bank)",
    "Luzon Development Bank",
    "Mactan Rural Bank (Lapu-Lapu City), Inc.",
    "Maharlika Rural Bank, Inc.",
    "Makiling Development Bank Corporation",
    "Malarayat Rural Bank, Inc.",
    "Malayan Savings Bank, Inc.",
    "Mallig Plains Rural Bank (Isabela), Inc.",
    "Manor Bank - A Rural Bank Corp.",
    "Marayo Bank, Inc. (A Rural Bank)",
    "Maritime Bank Corporation (A Rural Bank)",
    "Masagana Rural Bank, (Gen. Natividad, N.E.), Inc.",
    "Maybank Philippines, Incorporated",
    "Mega International Commercial Bank Co., Ltd.",
    "Mega Rural Bank (Lucena City), Inc.",
    "Metropolitan Bank and Trust Company",
    "Mindanao Consolidated Cooperative Bank",
    "Misamis Bank, Inc. A Rural Bank",
    "Mizuho Bank, Ltd. - Manila Branch",
    "Money Mall Rural Bank, Inc.",
    "Mount Carmel Rural Bank, Inc.",
    "MUFG Bank, Ltd.",
    "MVSM Bank (A Rural Bank Since 1953) Inc.",
    "Naawan Community Rural Bank (Misamis Oriental), Inc.",
    "National Teachers & Employees Cooperative Bank",
    "Negros Cooperative Bank",
    "Netbank (A Rural Bank), Inc.",
    "Network Consolidated Cooperative Bank",
    "New Rural Bank of Agoncillo, Inc.",
    "New Rural Bank of San Leonardo (Nueva Ecija), Inc.",
    "North Pacific Banking Corporation (A Rural Bank)",
    "Northpoint Development Bank, Inc.",
    "Occidental Mindoro Cooperative Bank (OMCB)",
    "One Cooperative Bank",
    "One Unified Rural Bank of Cavite Incorporated",
    "Oriental Tamaraw Rural Bank of Naujan, (Or. Mdo.), Inc.",
    "Ormon Bank (Rural Bank of Mulanay (Quezon), Inc.)",
    "Own Bank, The Rural Bank of Cavite City, Inc.",
    "Pacific Ace Savings Bank, Inc.",
    "Pampanga Development Bank",
    "Pangasinan Bank (A Rural Bank), Inc.",
    "Panguil Bay Rural Bank of Ozamiz, Inc.",
    "Partner Rural Bank (Cotabato), Inc.",
    "Penbank, Inc. (A Private Development Bank) (formerly: Peninsula Rural Bank, Inc.)",
    "People's Rural Bank (Gen. Santos City), Inc.",
    "People’s Hawak Kamay Bank, Inc.",
    "Phil Star Development Bank, Inc.",
    "Philippine Bank of Communications",
    "Philippine Business Bank, Inc., A Savings Bank",
    "Philippine National Bank",
    "Philippine Savings Bank",
    "Philippine SME Bank, Inc., A Rural Bank",
    "Philippine Trust Company",
    "Philippine Veterans Bank",
    "Pioneer Bank (A Rural Bank), Inc.",
    "Planbank \"Rural Bank of Canlubang Planters, Inc.\"",
    "Producers Savings Bank Corporation",
    "ProFarmers Rural Banking Corporation",
    "Progressive Rural Bank, Inc.",
    "Provident Rural Bank of Sta. Cruz (Laguna), Inc.",
    "Queen City Development Bank, Inc. or Queenbank, A Thrift Bank",
    "Queen City Rural Bank, Inc.",
    "Quezon Capital Rural Bank, Inc.",
    "Quezon Coconut Bank, Inc. (A Thrift Bank)",
    "Rang-Ay Bank, Inc. (A Rural Bank)",
    "RBT Bank, Inc., A Rural Bank",
    "Rizal Commercial Banking Corporation",
    "Rizal Microbank, Inc. - A Thrift Bank of RCBC",
    "RNG Bank",
    "Rural Bank of Agoo, Inc.",
    "Rural Bank of Alabel (Sarangani), Inc.",
    "Rural Bank of Alaminos (Pangasinan), Inc.",
    "Rural Bank of Alicia (Isabela), Inc.",
    "Rural Bank of Alitagtag, Inc.",
    "Rural Bank of Altavas (Aklan), Inc.",
    "Rural Bank of Amlan (Negros Oriental), Inc.",
    "Rural Bank of Anda (Pangasinan), Inc.",
    "Rural Bank of Angat (Bulacan), Inc.",
    "Rural Bank of Angeles, Inc.",
    "Rural Bank of Angono, Inc.",
    "Rural Bank of Antipolo, Inc.",
    "Rural Bank of Apalit, Inc.",
    "Rural Bank of Aritao, Inc.",
    "Rural Bank of Bacnotan, Inc.",
    "Rural Bank of Baco (Oriental Mindoro), Inc.",
    "Rural Bank of Bacolod City, Inc.",
    "Rural Bank of Bacong (Negros Oriental), Inc.",
    "Rural Bank of Bagabag (N.V.), Inc.",
    "Rural Bank of Bagac, Bataan, Inc.",
    "Rural Bank of Baguio, Inc.",
    "Rural Bank of Balungao (Pangasinan), Inc.",
    "Rural Bank of Bambang (Nueva Vizcaya), Inc.",
    "Rural Bank of Banga (Aklan), Inc.",
    "Rural Bank of Bansud (Oriental Mindoro), Inc.",
    "Rural Bank of Barili (Cebu), Inc.",
    "Rural Bank of Batac, Inc.",
    "Rural Bank of Bato (Leyte), Inc.",
    "Rural Bank of Bauang, Inc.",
    "Rural Bank of Bay, Inc.",
    "Rural Bank of Bayambang (Pangasinan), Inc.",
    "Rural Bank of Bayombong, Inc.",
    "Rural Bank of Bogo (Cebu), Inc.",
    "Rural Bank of Bolinao (Pangasinan), Inc.",
    "Rural Bank of Bonifacio (Misamis Occidental), Inc.",
    "Rural Bank of Bontoc (Mountain Province), Inc.",
    "Rural Bank of Brooke'S Point (Palawan), Inc.",
    "Rural Bank of Bucay (Abra), Inc.",
    "Rural Bank of Cabangan (Zambales), Inc.",
    "Rural Bank of Cabatuan (Iloilo), Inc.",
    "Rural Bank of Cabugao (Ilocos Sur), Inc.",
    "Rural Bank of Cadiz, Inc.",
    "Rural Bank of Calauan, Inc.",
    "Rural Bank of Calbayog City, Inc.",
    "Rural Bank of Calinog (Iloilo), Inc.",
    "Rural Bank of Candelaria, Inc.",
    "Rural Bank of Capalonga (Camarines Norte),Inc.",
    "Rural Bank of Cardona (Rizal), Inc.",
    "Rural Bank of Casiguran (Aurora), Inc.",
    "Rural Bank of Cauayan, Incorporated",
    "Rural Bank of Cavinti (Laguna), Inc.",
    "Rural Bank of Central Pangasinan (Bayambang), Inc.",
    "Rural Bank of Compostela (COMVAL), Inc.",
    "Rural Bank of Cuartero (Capiz), Inc.",
    "Rural Bank of Cuenca, Inc.",
    "Rural Bank of Digos, Inc.",
    "Rural Bank of Dolores (Quezon), Inc.",
    "Rural Bank of Donsol (Sorsogon), Inc.",
    "Rural Bank of Doña Remedios Trinidad (Bulacan), Inc.",
    "Rural Bank of Dulag (Leyte), Inc.",
    "Rural Bank of Dumangas, Inc.",
    "Rural Bank of Dupax (Nueva Vizcaya), Inc.",
    "Rural Bank of El Salvador (Misamis Oriental), Inc.",
    "Rural Bank of Escalante (Negros Occ.), Inc.",
    "Rural Bank of Gandara (Samar), Inc.",
    "Rural Bank of Gattaran (Cagayan), Inc.",
    "Rural Bank of General Luna (Quezon), Inc.",
    "Rural Bank of Gingoog, Inc.",
    "Rural Bank of Gitagum (Misamis Oriental), Inc.",
    "Rural Bank of Gloria (Or. Min.), Inc.",
    "Rural Bank of Guinobatan, Inc.",
    "Rural Bank of Guiuan (Eastern Samar), Inc.",
    "Rural Bank of Hermosa (Bataan), Inc.",
    "Rural Bank of Hilongos,Inc.",
    "Rural Bank of Hindang (Leyte), Inc.",
    "Rural Bank of Hinundayan (Southern Leyte), Inc.",
    "Rural Bank of Ibajay, Inc.",
    "Rural Bank of Ilog (Negros Occidental), Inc.",
    "Rural Bank of Iloilo City, Inc.",
    "Rural Bank of Infanta, Inc.",
    "Rural Bank of Irosin, Inc.",
    "Rural Bank of Itogon (Benguet), Inc.",
    "Rural Bank of Jaen, Inc.",
    "Rural Bank of Jamindan (Capiz), Inc.",
    "Rural Bank of Jimenez (Misamis Occidental), Inc.",
    "Rural Bank of Jose Panganiban (Camarines Norte), Inc.",
    "Rural Bank of Kapalong (Davao), Inc.",
    "Rural Bank of Kiamba (Sarangani), Inc.",
    "Rural Bank of Kibawe (Bukidnon), Inc.",
    "Rural Bank of La Paz, Inc.",
    "Rural Bank of Labason (Zamboanga Del Norte), Incorporated",
    "Rural Bank of Lanuza (Surigao Del Sur), Incorporated",
    "Rural Bank of Lebak (Sultan Kudarat), Incorporated",
    "Rural Bank of Leganes (Iloilo), Inc.",
    "Rural Bank of Liloy (Zamboanga Del Norte), Inc.",
    "Rural Bank of Lipa City (Batangas), Inc.",
    "Rural Bank of Loon (Bohol), Inc.",
    "Rural Bank of Lopez Jaena (Misamis Occidental), Inc.",
    "Rural Bank of Lucban (Quezon), Inc.",
    "Rural Bank of Luisiana (Laguna), Inc.",
    "Rural Bank of Lumban (Laguna), Inc.",
    "Rural Bank of Mabalacat, Inc.",
    "Rural Bank of Maddela (Quirino), Inc.",
    "Rural Bank of Madridejos (Cebu), Inc.",
    "Rural Bank of Magdalena (Laguna), Inc.",
    "Rural Bank of Makato (Aklan), Inc.",
    "Rural Bank of Malitbog (Southern Leyte), Inc.",
    "Rural Bank of Malolos, Inc.",
    "Rural Bank of Mambusao, Inc.",
    "Rural Bank of Manapla (Neg. Occ.), Inc.",
    "Rural Bank of Mangaldan, Inc. (Bangko Rural Ng Mangaldan, Ink.)",
    "Rural Bank of Manolo Fortich, Bukidnon, Inc.",
    "Rural Bank of Manukan (Zamboanga Del Norte), Inc.",
    "Rural Bank of Maria Aurora (Aurora), Inc.",
    "Rural Bank of Marilag (Sta. Maria, Laguna), Inc.",
    "Rural Bank of Matag-ob (Leyte), Inc.",
    "Rural Bank of Mati, Inc.",
    "Rural Bank of Mauban, Inc.",
    "Rural Bank of Medina (Misamis Oriental), Inc.",
    "Rural Bank of Miagao (Iloilo), Inc.",
    "Rural Bank of Midsayap, Inc.",
    "Rural Bank of Montalban, Inc.",
    "Rural Bank of Naic, Inc.",
    "Rural Bank of New Washington (Aklan), Inc.",
    "Rural Bank of Norala (S. Cotabato), Inc.",
    "Rural Bank of Padre Garcia, Inc.",
    "Rural Bank of Paete, Inc.",
    "Rural Bank of Pagadian, Inc.",
    "Rural Bank of Pamplona (Negros Oriental), Inc.",
    "Rural Bank of Paracale (Camarines Norte), Incorporated",
    "Rural Bank of Pilar (Bataan), Inc.",
    "Rural Bank of Pilar (Sorsogon), Inc.",
    "Rural Bank of Pinamalayan, Inc.",
    "Rural Bank of Placer (Surigao del Norte), Inc.",
    "Rural Bank of Pola (Oriental Mindoro), Inc.",
    "Rural Bank of Porac (Pampanga), Inc.",
    "Rural Bank of Puerto Galera (Oriental Mindoro), Inc.",
    "Rural Bank of Pura (Tarlac), Inc.",
    "Rural Bank of Quezon (N. E.), Inc.",
    "Rural Bank of Ramon (Isabela), Inc.",
    "Rural Bank of Rizal (Kalinga-Apayao), Inc.",
    "Rural Bank of Rizal (Laguna), Inc.",
    "Rural Bank of Rizal (Zamboanga Del Norte), Inc.",
    "Rural Bank of Rosario (La Union), Inc.",
    "Rural Bank of Roxas (Oriental Mindoro), Inc.",
    "Rural Bank of Sagada (Mountain Province), Inc.",
    "Rural Bank of Sagay, Inc.",
    "Rural Bank of Salug (Zamboanga Del Norte), Inc.",
    "Rural Bank of Sampaloc (Quezon), Inc.",
    "Rural Bank of San Antonio, Inc.",
    "Rural Bank of San Jacinto (Masbate), Inc.",
    "Rural Bank of San Jose (Camarines Sur), Inc.",
    "Rural Bank of San Luis (Batangas), Inc.",
    "Rural Bank of San Luis (Pampanga), Inc.",
    "Rural Bank of San Manuel (Isabela), Inc.",
    "Rural Bank of San Mateo (Isabela), Inc.",
    "Rural Bank of San Miguel (Iloilo), Inc.",
    "Rural Bank of San Narciso, Inc.",
    "Rural Bank of San Pascual (Obando, Bulacan), Inc.",
    "Rural Bank of San Rafael (Bulacan), Inc.",
    "Rural Bank of Sanchez Mira (Cagayan), Inc.",
    "Rural Bank of Sasmuan (Pampanga), Incorporated",
    "Rural Bank of Seven Lakes (San Pablo City), Inc.",
    "Rural Bank of Silay City, Inc.",
    "Rural Bank of Sipocot (Camarines Sur), Inc.",
    "Rural Bank of Socorro (Oriental Mindoro), Inc.",
    "Rural Bank of Solano (Nueva Vizcaya), Inc.",
    "Rural Bank of Sta. Barbara (Iloilo), Inc.",
    "Rural Bank of Sta. Ignacia, Inc.",
    "Rural Bank of Sta. Maria (Ilocos Sur), Inc.",
    "Rural Bank of Sta. Rosa (Laguna), Inc.",
    "Rural Bank of Sta. Rosa De Lima (Paniqui, Tarlac), Inc.",
    "Rural Bank of Sudipen (La Union), Inc.",
    "Rural Bank of Taal, Inc.",
    "Rural Bank of Talugtug (N. E.), Inc.",
    "Rural Bank of Tandag (Surigao Del Sur), Inc.",
    "Rural Bank of Tangub City, (Mis. Occ.) Inc.",
    "Rural Bank of Tanjay, Inc.",
    "Rural Bank of Tigaon Camarines Sur, Inc.",
    "Rural Bank of Tigbauan (Iloilo), Inc.",
    "Rural Bank of Victoria, Inc.",
    "Rural Bank of Villaverde (Nueva Vizcaya), Inc.",
    "Rural Bank of Zarraga (Iloilo), Inc.",
    "Sadiri Rural Bank (San Juan, Ilocos Sur), Inc.",
    "Salug Valley Rural Bank, Inc.",
    "San Bartolome Rural Bank, Inc.",
    "Saviour Rural Bank, Inc.",
    "SeaBank Philippines Inc. (A Rural Bank)",
    "Second Rural Bank of San Luis, Pampanga, Inc.",
    "Second Rural Bank of Valenzuela (Metro Manila), Inc.",
    "Secured Bank, Inc. (A Rural Bank)",
    "Security Bank Corporation",
    "SG Bank - A Rural bank Inc.",
    "Shinhan Bank - Manila Branch",
    "Silahis Bank, Inc. (A Rural Bank)",
    "South Bank (A Rural Bank), Incorporated",
    "Southeast Country Bank, Inc. ( A Rural Bank)",
    "St. Michael Rural Bank of Tarlac (Tarlac), Inc.",
    "Sta. Maria Rural Bank, Inc.",
    "Standard Chartered Bank",
    "Sterling Bank of Asia, Inc. (A Savings Bank)",
    "Sumitomo Mitsui Banking Corporation-Manila Branch",
    "Summit Bank (Rural Bank of Tublay, Inc.)",
    "Summit Rural Bank of Lipa City, Inc.",
    "Sun Savings Bank, Inc.",
    "Sunrise Rural Bank (Rosario, Batangas), Inc.",
    "Talisay Rural Bank, Inc.",
    "Tamaraw Rural Bank, Inc.",
    "The Country Bank Rural Bank of Bongabong Or. Mindoro, Inc.",
    "The Hongkong & Shanghai Banking Corporation",
    "Top Bank Philippines, Inc. (A Rural Bank)",
    "Towncall Rural Bank, Inc.",
    "TRBank Inc. (A Rural Bank)",
    "Turumba Rural Bank of Pakil, Inc.",
    "UCPB Savings Bank",
    "Unilink Bank, Inc. (A Rural Bank)",
    "Union Bank of the Philippines",
    "United Overseas Bank Limited, Manila Branch",
    "Universal Rural Bank of Lopez (Quezon), Inc.",
    "University Savings Bank, Inc.",
    "Upland Rural Bank of Dalaguete (Cebu), Inc.",
    "Utility Bank, Inc. (A Rural Bank)",
    "Vigan Banco Rural, Incorporada",
    "Village Bank, Inc. (A Rural Bank)",
    "Vizcaya Bank, A Rural Bank, Inc.",
    "Wealth Development Bank Corporation",
    "Welcome Bank (Rural Bank), Inc.",
    "Yuanta Savings Bank Philippines, Inc.",
    "Zambales Rural Bank, Inc.",
    "Zamboanga City Rural Bank, Inc.",
    "Zamboanga Del Norte Cooperative Bank"
]